name: Create or update milestone-renovate branch

on:
  push:
    branches:
      - main
  delete:

jobs:
  create-or-update-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - env:
          GITHUB_EVENT: ${{ toJSON(github) }}
        run: echo "$GITHUB_EVENT"
      - name: Create milestone-renovate
        if: ${{ github.event.ref_type == 'branch' && github.event.ref == 'milestone-renovate' }}
        run: echo 'Create milestone-renovate'
      - name: Update milestone-renovate
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: echo 'Update milestone-renovate'
