name: Create or update milestone-renovate branch

on:
  push:
    branches:
      - release
  delete:

jobs:
  create-or-update-branch:
    if: ${{ github.event_name == 'push' || github.event.ref_type == 'branch' && github.event.ref == 'milestone-renovate' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create or update milestone-renovate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEFAULT_BRANCH='release'
          BRANCH_NAME='milestone-renovate'
          if [ ! "$(git branch -a --format="%(refname:short)" | grep -e ^${BRANCH_NAME}$)" ] ; then
            git checkout -b ${BRANCH_NAME}
            git push origin ${BRANCH_NAME}
          else
            git checkout ${BRANCH_NAME}
            git rebase ${DEFAULT_BRANCH}
            git push -f origin ${BRANCH_NAME}
          fi
